### ISSUE TITLE
Project DEPLOYMENT page

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#187]
# Requirements
- [x] Create page
- [ ] Access HA via SSH #188 
- [ ] Maintaining HA using GitHub #189 
- [ ] Version Control + Deployment #190
