### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by theglus** [theglus/Home-Assistant-Config#281]
# Requirements
### Cleanup
- [x] Clean-up projects
- [x] Polk S50 image
- [x] Update Polk speakers in AV section
### Resources
- [x] Add resources section
- [x] Add integrations
- [x] Add custom integrations
### Demo
- [x] Add demo section 
- [x] GIF of switcher
- [x] GIF of pop-ups: #418 
- [x] Picture of tablet: #419
### System Controls
- [x] Create System Control section: #416
- [x] Explain HA controls: #416
- [x] Explain PC controls: #416
### Automations
- [x] List out automations
- [x] Link out automations 
### Architecture Diagram
- [x] Add LG ThinQ
- [x] Add Nanoleaf
- [x] Add Roborock
- [x] Switchbot
- [x] Dyson
- [x] Denon
- [x] MQTT: #415 
- [x] PC integration: #415 
### Inspiration
- [x] Add repo link-out to inspiration: #417

# Resources
- [homeassistant-config-v2](https://github.com/eximo84/homeassistant-config-v2)
- [Eliot's Homeassistant Configuration](https://github.com/eIiot/homeassistant)
- [Crixle's Dashboard](https://github.com/crixle/homeassistant-config)
- [The Blob - I Am Your House](https://github.com/fastender/blob)

**Comment by theglus** [comment]
Broke remaining work into the following issues:

- #415 
- #416 
- #417 
- #418 
- #419
